version: '2'

services:
  server:
    container_name: provider
    image: python:3.8-slim-bullseye
    volumes:
      - ./provider:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: bash
    tty: true

  relying_party:
    container_name: relying_party
    image: python:3.8-slim-bullseye
    volumes:
      - ./relying_party:/app
    working_dir: /app
    ports:
      - "8082:8080"
    command: bash
    tty: true

  redis:
      container_name: redis
      image: redis:4.0.1
