version: '2'

services:
  server:
    container_name: server
    image: python:3.8-slim-bullseye
    volumes:
      - ./src/:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: bash
    tty: true

  redis:
      container_name: redis
      image: redis:4.0.1
